using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Toarnbeike.Immutable.SourceGeneration.Extensions;

namespace Toarnbeike.Immutable.SourceGeneration.Entities;

/// <summary>
/// Generates a partial implementation of an Entity{TKey},
/// given that the entity contains an [Aggregate] attribute.
/// Provides private constructors and static factory methods. 
/// </summary>
[Generator]
[ExcludeFromCodeCoverage]
public class AggregateGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        //if (!Debugger.IsAttached) Debugger.Launch();
        
        var aggregates = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AggregateInfo.AggregateAttributeFqn,
                predicate: static (node, _) => true,
                transform: (ctx, _) => AggregateInfo.Create((INamedTypeSymbol)ctx.TargetSymbol)
            ).Where(static aggregate => aggregate is not null);
        
        context.RegisterSourceOutput(aggregates, static (spc, aggregate) => Execute(spc, aggregate!));
    }
    
    private static void Execute(SourceProductionContext context, AggregateInfo aggregateInfo)
    {
        var source = GenerateAggregateImplementation(aggregateInfo);
        var fileName = $"{aggregateInfo.Namespace}.{aggregateInfo.Name}.g.cs";
        
        context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateAggregateImplementation(AggregateInfo aggregateInfo)
    {
        var props = aggregateInfo.Properties.Where(prop => !prop.IsReadOnly).ToList();

        // Voor CreateNew gebruiken we alle init-only properties
        var initParams = props.ToParameterList();
        var assignments = props.ToAssignments();

        // Voor CreateExisting voegen we de Id toe als eerste parameter
        var existingParams = $"{aggregateInfo.Name}Id id" +
                             (props.Count > 0 ? ", " + initParams : "");

        return $$"""
                 // <auto-generated />
                 // generator: Toarnbeike.Immutable.SourceGeneration.Entities.AggregateGenerator
                 #nullable enable

                 namespace {{aggregateInfo.Namespace}};

                 public partial record {{aggregateInfo.Name}}
                 {
                     /// <summary>
                     /// Create a new instance of the {{aggregateInfo.Name}}.
                     /// </summary>
                     public static {{aggregateInfo.Name}} CreateNew({{initParams}}) =>
                         new({{string.Join(", ", props.Select(p => p.Name.ToParameterName()))}});

                     /// <summary>
                     /// Recreate an existing instance of the {{aggregateInfo.Name}}.
                     /// </summary>
                     public static {{aggregateInfo.Name}} CreateExisting({{aggregateInfo.Name}}Id id{{(props.Count > 0 ? ", " + initParams : "")}}) =>
                         new(id{{(props.Count > 0 ? ", " + string.Join(", ", props.Select(p => p.Name.ToParameterName())) : "")}});

                     private {{aggregateInfo.Name}}({{existingParams}})
                         : base(id)
                     {
                 {{assignments}}
                     }

                     private {{aggregateInfo.Name}}({{initParams}})
                     {
                 {{assignments}}
                     }
                 }
                 """;
    }
}